# Generated by Django 4.2.7 on 2023-12-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mpgapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "ModelName", "verbose_name_plural": "ModelNames"},
        ),
        migrations.AlterModelTable(name="article", table=None,),
    ]
