# Generated by Django 2.1.5 on 2023-12-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpgapp', '0002_alter_article_options_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
    ]
